name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.4
          channel: 'stable'
          cache: true

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d # Note: Using the exact version 27.0.12077973 from your logs
          add-to-path: false

      - name: Cache CMake
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/android/sdk/cmake/
          key: ${{ runner.os }}-cmake-3.22.1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache/hosted
            ~/.pub-cache/git
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test || true

      - name: Build APK
        run: flutter build apk --release --no-pub

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:647460537786:android:e525a74d6979a72ca98983
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
